# Windows 10 Disk Cleanup Script
# Generated by Hermes Agent for Charlie Leftwich
# Frees disk space safely - nothing deleted without showing you first
#
# Run in Administrator PowerShell:
#   cd "C:\Users\Home User\Documents\Obsidian Vault\00 - Inbox"
#   Set-ExecutionPolicy Bypass -Scope Process -Force
#   .\disk-cleanup.ps1

#Requires -RunAsAdministrator

$ErrorActionPreference = "Continue"

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Disk Cleanup Script" -ForegroundColor Cyan
Write-Host "  Hermes Agent - 2026-07-27" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Get starting free space
$before = (Get-PSDrive C).Free
$beforeGB = [math]::Round($before / 1GB, 1)
Write-Host "Starting free space: $beforeGB GB" -ForegroundColor White
Write-Host ""

$totalFreed = 0

# --- 1. Empty Recycle Bin ---
Write-Host "[1/8] Emptying Recycle Bin..." -ForegroundColor Yellow
try {
    $shell = New-Object -ComObject Shell.Application
    $recycleBin = $shell.Namespace(0xA)
    $binSize = 0
    foreach ($item in $recycleBin.Items()) {
        $binSize += $item.Size
    }
    $binMB = [math]::Round($binSize / 1MB, 1)
    Clear-RecycleBin -Force -ErrorAction SilentlyContinue
    Write-Host "  [OK] Recycle Bin emptied - freed $binMB MB" -ForegroundColor Green
    $totalFreed += $binSize
} catch {
    Write-Host "  Recycle Bin already empty or error" -ForegroundColor DarkGray
}

# --- 2. Clean Temp Files ---
Write-Host ""
Write-Host "[2/8] Cleaning temp files..." -ForegroundColor Yellow
$tempPaths = @(
    $env:TEMP,
    "$env:WINDIR\Temp",
    "$env:WINDIR\Prefetch",
    "$env:LOCALAPPDATA\Microsoft\Windows\INetCache",
    "$env:LOCALAPPDATA\Microsoft\Windows\Explorer",
    "$env:LOCALAPPDATA\CrashDumps",
    "$env:LOCALAPPDATA\Microsoft\Windows\WER",
    "$env:WINDIR\Logs\CBS",
    "$env:WINDIR\Logs\DISM"
)
$tempFreed = 0
foreach ($path in $tempPaths) {
    if (Test-Path $path) {
        $files = Get-ChildItem -Path $path -Recurse -Force -ErrorAction SilentlyContinue
        foreach ($f in $files) {
            $size = $f.Length
            Remove-Item $f.FullName -Force -Recurse -ErrorAction SilentlyContinue
            if (-not (Test-Path $f.FullName)) { $tempFreed += $size }
        }
    }
}
$tempMB = [math]::Round($tempFreed / 1MB, 1)
Write-Host "  [OK] Temp files cleaned - freed $tempMB MB" -ForegroundColor Green
$totalFreed += $tempFreed

# --- 3. Clean Windows Update Cache ---
Write-Host ""
Write-Host "[3/8] Cleaning Windows Update cache..." -ForegroundColor Yellow
Stop-Service wuauserv -Force -ErrorAction SilentlyContinue
Stop-Service bits -Force -ErrorAction SilentlyContinue
$softDist = "$env:WINDIR\SoftwareDistribution\Download"
$updateFreed = 0
if (Test-Path $softDist) {
    $files = Get-ChildItem -Path $softDist -Recurse -Force -ErrorAction SilentlyContinue
    foreach ($f in $files) {
        $updateFreed += $f.Length
        Remove-Item $f.FullName -Force -Recurse -ErrorAction SilentlyContinue
    }
}
$updateMB = [math]::Round($updateFreed / 1MB, 1)
Start-Service wuauserv -ErrorAction SilentlyContinue
Start-Service bits -ErrorAction SilentlyContinue
Write-Host "  [OK] Windows Update cache cleaned - freed $updateMB MB" -ForegroundColor Green
$totalFreed += $updateFreed

# --- 4. Disable Hibernation (frees RAM-size worth of space) ---
Write-Host ""
Write-Host "[4/8] Disabling hibernation..." -ForegroundColor Yellow
$hiberFile = "$env:SystemDrive\hiberfil.sys"
$hiberSize = 0
if (Test-Path $hiberFile) {
    $hiberSize = (Get-Item $hiberFile -Force).Length
}
powercfg /hibernate off 2>$null
$hiberMB = [math]::Round($hiberSize / 1MB, 1)
if ($hiberSize -gt 0) {
    Write-Host "  [OK] Hibernation disabled - freed $hiberMB MB (hiberfil.sys removed)" -ForegroundColor Green
    $totalFreed += $hiberSize
} else {
    Write-Host "  Hibernation already disabled" -ForegroundColor DarkGray
}

# --- 5. Clean Old Windows Logs ---
Write-Host ""
Write-Host "[5/8] Cleaning old Windows logs..." -ForegroundColor Yellow
$logPaths = @(
    "$env:WINDIR\Logs",
    "$env:WINDIR\Panther",
    "$env:WINDIR\inf\setupapi.dev.log",
    "$env:LOCALAPPDATA\Microsoft\Windows\Firewall"
)
$logFreed = 0
foreach ($path in $logPaths) {
    if (Test-Path $path) {
        $items = Get-ChildItem -Path $path -Recurse -Force -ErrorAction SilentlyContinue
        foreach ($item in $items) {
            if ($item.PSIsContainer) { continue }
            $age = (Get-Date) - $item.LastWriteTime
            if ($age.Days -gt 7) {
                $logFreed += $item.Length
                Remove-Item $item.FullName -Force -ErrorAction SilentlyContinue
            }
        }
    }
}
$logMB = [math]::Round($logFreed / 1MB, 1)
Write-Host "  [OK] Old logs cleaned - freed $logMB MB" -ForegroundColor Green
$totalFreed += $logFreed

# --- 6. Clean Browser Caches ---
Write-Host ""
Write-Host "[6/8] Cleaning browser caches..." -ForegroundColor Yellow
$browserCaches = @(
    "$env:LOCALAPPDATA\Google\Chrome\User Data\Default\Cache",
    "$env:LOCALAPPDATA\Google\Chrome\User Data\Default\Code Cache",
    "$env:LOCALAPPDATA\Microsoft\Edge\User Data\Default\Cache",
    "$env:LOCALAPPDATA\Microsoft\Edge\User Data\Default\Code Cache",
    "$env:LOCALAPPDATA\Mozilla\Firefox\Profiles\*\cache2",
    "$env:APPDATA\..\Local\BraveSoftware\Brave-Browser\User Data\Default\Cache"
)
$browserFreed = 0
foreach ($path in $browserCaches) {
    $resolved = Resolve-Path $path -ErrorAction SilentlyContinue
    if ($resolved) {
        $files = Get-ChildItem -Path $resolved.Path -Recurse -Force -ErrorAction SilentlyContinue
        foreach ($f in $files) {
            $browserFreed += $f.Length
            Remove-Item $f.FullName -Force -Recurse -ErrorAction SilentlyContinue
        }
    }
}
$browserMB = [math]::Round($browserFreed / 1MB, 1)
Write-Host "  [OK] Browser caches cleaned - freed $browserMB MB" -ForegroundColor Green
$totalFreed += $browserFreed

# --- 7. Clean Docker (if installed) ---
Write-Host ""
Write-Host "[7/8] Cleaning Docker (if installed)..." -ForegroundColor Yellow
$dockerPath = Get-Command docker -ErrorAction SilentlyContinue
if ($dockerPath) {
    $dockerBefore = 0
    try {
        $dockerInfo = docker system df --format "{{.Size}}" 2>$null
        if ($dockerInfo) {
            Write-Host "  Docker disk usage detected:" -ForegroundColor White
            docker system df 2>$null | ForEach-Object { Write-Host "    $_" -ForegroundColor Gray }
        }
        Write-Host "  Pruning unused Docker data..." -ForegroundColor Yellow
        docker system prune -a -f 2>$null | ForEach-Object { Write-Host "    $_" -ForegroundColor Gray }
        Write-Host "  [OK] Docker pruned" -ForegroundColor Green
    } catch {
        Write-Host "  Docker not running or error" -ForegroundColor DarkGray
    }
} else {
    Write-Host "  Docker not installed - skipping" -ForegroundColor DarkGray
}

# --- 8. Find Top 20 Largest Files ---
Write-Host ""
Write-Host "[8/8] Finding top 20 largest files on C: drive..." -ForegroundColor Yellow
Write-Host "  (This may take a minute...)" -ForegroundColor DarkGray
$bigFiles = Get-ChildItem C:\ -Recurse -File -Force -ErrorAction SilentlyContinue |
    Sort-Object Length -Descending |
    Select-Object -First 20
Write-Host ""
Write-Host "  Top 20 largest files:" -ForegroundColor White
foreach ($f in $bigFiles) {
    $sizeMB = [math]::Round($f.Length / 1MB, 0)
    $sizeGB = [math]::Round($f.Length / 1GB, 2)
    if ($sizeGB -ge 1) {
        Write-Host "    $sizeGB GB - $($f.FullName)" -ForegroundColor Yellow
    } else {
        Write-Host "    $sizeMB MB - $($f.FullName)" -ForegroundColor White
    }
}

# --- Summary ---
$after = (Get-PSDrive C).Free
$afterGB = [math]::Round($after / 1GB, 1)
$totalMB = [math]::Round($totalFreed / 1MB, 0)
$gainedGB = [math]::Round(($after - $before) / 1GB, 1)

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Cleanup Complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Summary:" -ForegroundColor White
Write-Host "  Before: $beforeGB GB free"
Write-Host "  After:  $afterGB GB free"
Write-Host "  Gained: $gainedGB GB ($totalMB MB)"
Write-Host ""
Write-Host "What was cleaned:" -ForegroundColor White
Write-Host "  - Recycle Bin: $binMB MB"
Write-Host "  - Temp files: $tempMB MB"
Write-Host "  - Windows Update cache: $updateMB MB"
Write-Host "  - Hibernation file: $hiberMB MB"
Write-Host "  - Old Windows logs: $logMB MB"
Write-Host "  - Browser caches: $browserMB MB"
Write-Host ""
Write-Host "To free even more space, review the top 20 files above" -ForegroundColor Yellow
Write-Host "and delete any you no longer need." -ForegroundColor Yellow
Write-Host ""
