# Windows 10 Optimization Script
# Generated by Hermes Agent for Charlie Leftwich
# Date: 2026-07-27
# 
# This script safely optimizes Windows 10 without breaking anything.
# It creates a restore point first, then cleans and optimizes.
# Run in Administrator PowerShell.
#
# To run:
#   1. Right-click PowerShell → Run as Administrator
#   2. cd "C:\Users\Home User\Documents\Obsidian Vault"
#   3. git pull origin main
#   4. Set-ExecutionPolicy Bypass -Scope Process -Force
#   5. .\optimize-windows.ps1
#
# To UNDO anything, use the restore point:
#   Start → type "System Restore" → choose the restore point created by this script

#Requires -RunAsAdministrator

$ErrorActionPreference = "Continue"

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Windows 10 Optimization Script" -ForegroundColor Cyan
Write-Host "  Hermes Agent — 2026-07-27" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# ─── 1. Create Restore Point ─────────────────────────────────────────────
Write-Host "[1/9] Creating System Restore Point..." -ForegroundColor Yellow
Enable-ComputerRestore -Drive "C:\"
Checkpoint-Computer -Description "Hermes Optimization Pre-Script" -RestorePointType "MODIFY_SETTINGS"
Write-Host "  ✅ Restore point created" -ForegroundColor Green

# ─── 2. Clean Temp Files ─────────────────────────────────────────────────
Write-Host ""
Write-Host "[2/9] Cleaning temporary files..." -ForegroundColor Yellow
$tempPaths = @(
    "$env:TEMP",
    "$env:WINDIR\Temp",
    "$env:WINDIR\Prefetch",
    "$env:LOCALAPPDATA\Microsoft\Windows\INetCache",
    "$env:LOCALAPPDATA\Microsoft\Windows\Explorer",
    "$env:LOCALAPPDATA\Temp"
)
$freed = 0
foreach ($path in $tempPaths) {
    if (Test-Path $path) {
        $files = Get-ChildItem -Path $path -Recurse -Force -ErrorAction SilentlyContinue
        foreach ($f in $files) {
            $size = $f.Length
            Remove-Item $f.FullName -Force -Recurse -ErrorAction SilentlyContinue
            if (-not (Test-Path $f.FullName)) { $freed += $size }
        }
    }
}
$freedMB = [math]::Round($freed / 1MB, 1)
Write-Host "  ✅ Cleaned temp files — freed $freedMB MB" -ForegroundColor Green

# ─── 3. Clean Windows Update Cache ───────────────────────────────────────
Write-Host ""
Write-Host "[3/9] Cleaning Windows Update cache..." -ForegroundColor Yellow
Stop-Service wuauserv -Force -ErrorAction SilentlyContinue
Stop-Service bits -Force -ErrorAction SilentlyContinue
$softDist = "$env:WINDIR\SoftwareDistribution\Download"
if (Test-Path $softDist) {
    Remove-Item "$softDist\*" -Recurse -Force -ErrorAction SilentlyContinue
}
Start-Service wuauserv -ErrorAction SilentlyContinue
Start-Service bits -ErrorAction SilentlyContinue
Write-Host "  ✅ Windows Update cache cleaned" -ForegroundColor Green

# ─── 4. Disable Unnecessary Startup Programs ─────────────────────────────
Write-Host ""
Write-Host "[4/9] Checking startup programs..." -ForegroundColor Yellow
$startupApps = Get-CimInstance Win32_StartupCommand | Where-Object {
    $_.Name -notmatch "OneDrive|SecurityHealth|WindowsDefender|System32|Program Files"
}
if ($startupApps) {
    Write-Host "  Found startup programs (NOT auto-removing — listing for review):" -ForegroundColor Yellow
    foreach ($app in $startupApps) {
        Write-Host "    • $($app.Name)" -ForegroundColor White
        Write-Host "      Command: $($app.Command)" -ForegroundColor Gray
        Write-Host "      Location: $($app.Location)" -ForegroundColor Gray
    }
    Write-Host "  To disable: Task Manager → Startup tab → right-click → Disable" -ForegroundColor DarkGray
} else {
    Write-Host "  ✅ No unnecessary startup programs found" -ForegroundColor Green
}

# ─── 5. Optimize Power Settings ───────────────────────────────────────────
Write-Host ""
Write-Host "[5/9] Optimizing power settings..." -ForegroundColor Yellow
# Set power plan to High Performance
powercfg /setactive 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c 2>$null
Write-Host "  ✅ Power plan set to High Performance" -ForegroundColor Green

# Disable hibernation (frees up disk space equal to RAM)
powercfg /hibernate off 2>$null
Write-Host "  ✅ Hibernation disabled (frees disk space)" -ForegroundColor Green

# Set monitor timeout (10 min on battery, 15 min plugged in)
powercfg /change monitor-timeout-battery 10
powercfg /change monitor-timeout-ac 15
Write-Host "  ✅ Monitor timeout: 10 min (battery), 15 min (plugged in)" -ForegroundColor Green

# ─── 6. Optimize Windows Services ────────────────────────────────────────
Write-Host ""
Write-Host "[6/9] Optimizing Windows services..." -ForegroundColor Yellow
# Only disable services that are SAFE to disable — nothing critical
$safeToDisable = @(
    @{Name="DiagTrack"; Desc="Connected User Experiences and Telemetry"},
    @{Name="dmwappushservice"; Desc="Device Management WAP Push Service"},
    @{Name="SysMain"; Desc="Superfetch (only disable if SSD)"}
)

foreach ($svc in $safeToDisable) {
    $service = Get-Service -Name $svc.Name -ErrorAction SilentlyContinue
    if ($service) {
        Stop-Service -Name $svc.Name -Force -ErrorAction SilentlyContinue
        Set-Service -Name $svc.Name -StartupType Disabled -ErrorAction SilentlyContinue
        Write-Host "  ✅ Disabled: $($svc.Desc) ($($svc.Name))" -ForegroundColor Green
    }
}

# Check if SSD — don't disable SysMain if HDD
$disk = Get-PhysicalDisk | Where-Object { $_.MediaType -eq "HDD" }
if ($disk) {
    Write-Host "  ⚠️ HDD detected — re-enabling SysMain (Superfetch) for HDD performance" -ForegroundColor Yellow
    Set-Service -Name "SysMain" -StartupType Automatic -ErrorAction SilentlyContinue
    Start-Service -Name "SysMain" -ErrorAction SilentlyContinue
}

# ─── 7. Disk Health Check & Optimization ─────────────────────────────────
Write-Host ""
Write-Host "[7/9] Checking disk health..." -ForegroundColor Yellow
$disks = Get-PhysicalDisk
foreach ($d in $disks) {
    Write-Host "  Disk: $($d.FriendlyName) | Type: $($d.MediaType) | Health: $($d.HealthStatus)" -ForegroundColor White
}

# Run TRIM if SSD, defrag if HDD
$ssd = Get-PhysicalDisk | Where-Object { $_.MediaType -eq "SSD" }
if ($ssd) {
    Write-Host "  Running TRIM optimization on SSD..." -ForegroundColor Yellow
    Optimize-Volume -DriveLetter C -ReTrim -Verbose -ErrorAction SilentlyContinue
    Write-Host "  ✅ TRIM complete" -ForegroundColor Green
} else {
    Write-Host "  Running defrag on HDD..." -ForegroundColor Yellow
    Optimize-Volume -DriveLetter C -Defrag -Verbose -ErrorAction SilentlyContinue
    Write-Host "  ✅ Defrag complete" -ForegroundColor Green
}

# Check free space
$drive = Get-PSDrive C
$freeGB = [math]::Round($drive.Free / 1GB, 1)
$totalGB = [math]::Round(($drive.Free + $drive.Used) / 1GB, 1)
Write-Host "  Disk C: $freeGB GB free of $totalGB GB total" -ForegroundColor White

# ─── 8. System Health Report ─────────────────────────────────────────────
Write-Host ""
Write-Host "[8/9] System health report..." -ForegroundColor Yellow

# CPU info
$cpu = Get-CimInstance Win32_Processor
Write-Host "  CPU: $($cpu.Name)" -ForegroundColor White
Write-Host "  Cores: $($cpu.NumberOfCores) | Threads: $($cpu.NumberOfLogicalProcessors)" -ForegroundColor White

# RAM info
$ram = Get-CimInstance Win32_ComputerSystem
$ramGB = [math]::Round($ram.TotalPhysicalMemory / 1GB, 1)
Write-Host "  RAM: $ramGB GB total" -ForegroundColor White

$os = Get-CimInstance Win32_OperatingSystem
$freeRamGB = [math]::Round($os.FreePhysicalMemory / 1MB, 1)
Write-Host "  RAM Available: $freeRamGB GB" -ForegroundColor White

# Windows version
$winVer = Get-CimInstance Win32_OperatingSystem
Write-Host "  Windows: $($winVer.Caption) Build $($winVer.BuildNumber)" -ForegroundColor White

# Last boot time
$lastBoot = $winVer.LastBootUpTime
$uptime = (Get-Date) - $lastBoot
Write-Host "  Uptime: $($uptime.Days) days, $($uptime.Hours) hours" -ForegroundColor White
Write-Host "  Last boot: $($lastBoot.ToString('yyyy-MM-dd HH:mm'))" -ForegroundColor White

# Check for Windows updates pending
$updateSession = New-Object -ComObject Microsoft.Update.Session
$searcher = $updateSession.CreateUpdateSearcher()
try {
    $updates = $searcher.Search("IsInstalled=0")
    if ($updates.Updates.Count -gt 0) {
        Write-Host "  ⚠️ $($updates.Updates.Count) Windows updates pending" -ForegroundColor Yellow
    } else {
        Write-Host "  ✅ Windows is up to date" -ForegroundColor Green
    }
} catch {
    Write-Host "  (Could not check Windows Update status)" -ForegroundColor DarkGray
}

# ─── 9. Network Optimization ─────────────────────────────────────────────
Write-Host ""
Write-Host "[9/9] Optimizing network settings..." -ForegroundColor Yellow

# Flush DNS cache
ipconfig /flushdns | Out-Null
Write-Host "  ✅ DNS cache flushed" -ForegroundColor Green

# Reset network adapters (winsock reset)
netsh winsock reset | Out-Null
Write-Host "  ✅ Winsock reset (restart required to take effect)" -ForegroundColor Green

# Set DNS to Cloudflare (fast, private) — optional, can revert later
$adapter = Get-NetAdapter | Where-Object { $_.Status -eq "Up" } | Select-Object -First 1
if ($adapter) {
    Set-DnsClientServerAddress -InterfaceIndex $adapter.ifIndex -ServerAddresses ("1.1.1.1", "1.0.0.1") -ErrorAction SilentlyContinue
    Write-Host "  ✅ DNS set to Cloudflare (1.1.1.1) — fast and private" -ForegroundColor Green
    Write-Host "  To revert: netsh interface ip set dns name='$($adapter.Name)' dhcp" -ForegroundColor DarkGray
}

# ─── Summary ─────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Optimization Complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Summary:" -ForegroundColor White
Write-Host "  • System restore point created"
Write-Host "  • Temp files cleaned ($freedMB MB freed)"
Write-Host "  • Windows Update cache cleaned"
Write-Host "  • Power plan: High Performance"
Write-Host "  • Hibernation: Disabled (disk space saved)"
Write-Host "  • Telemetry services: Disabled"
Write-Host "  • Disk: TRIM/defrag complete"
Write-Host "  • DNS: Flushed + Cloudflare"
Write-Host "  • Winsock: Reset"
Write-Host ""
Write-Host "Recommendation: RESTART your computer" -ForegroundColor Yellow
Write-Host "  to apply all changes." -ForegroundColor Yellow
Write-Host ""
Write-Host "To undo: System Restore → 'Hermes Optimization Pre-Script'" -ForegroundColor DarkGray
Write-Host ""
