# Windows 10 System Status Check
# Generated by Hermes Agent for Charlie Leftwich
# Run in regular PowerShell (no Admin needed)

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Windows 10 System Status" -ForegroundColor Cyan
Write-Host "  Hermes Agent - 2026-07-27" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# --- CPU ---
Write-Host "[CPU]" -ForegroundColor Yellow
$cpu = Get-CimInstance Win32_Processor
Write-Host "  Model: $($cpu.Name)"
Write-Host "  Cores: $($cpu.NumberOfCores) | Threads: $($cpu.NumberOfLogicalProcessors)"
$cpuLoad = [math]::Round($cpu.LoadPercentage, 0)
Write-Host "  Current Load: $cpuLoad%"

# --- RAM ---
Write-Host ""
Write-Host "[RAM]" -ForegroundColor Yellow
$ram = Get-CimInstance Win32_ComputerSystem
$ramGB = [math]::Round($ram.TotalPhysicalMemory / 1GB, 1)
$os = Get-CimInstance Win32_OperatingSystem
$freeRamGB = [math]::Round($os.FreePhysicalMemory / 1MB, 1)
$usedRamGB = [math]::Round($ramGB - $freeRamGB, 1)
$ramPct = [math]::Round(($usedRamGB / $ramGB) * 100, 0)
Write-Host "  Total: $ramGB GB"
Write-Host "  Used: $usedRamGB GB ($ramPct%)"
Write-Host "  Free: $freeRamGB GB"

# --- Disk ---
Write-Host ""
Write-Host "[DISK]" -ForegroundColor Yellow
$drive = Get-PSDrive C
$freeGB = [math]::Round($drive.Free / 1GB, 1)
$totalGB = [math]::Round(($drive.Free + $drive.Used) / 1GB, 1)
$usedGB = [math]::Round($totalGB - $freeGB, 1)
$diskPct = [math]::Round(($usedGB / $totalGB) * 100, 0)
Write-Host "  Drive C: $usedGB GB used / $totalGB GB total ($diskPct%)"
Write-Host "  Free: $freeGB GB"
$disks = Get-PhysicalDisk
foreach ($d in $disks) {
    Write-Host "  Physical: $($d.FriendlyName) | Type: $($d.MediaType) | Health: $($d.HealthStatus)"
}

# --- Disk I/O (if available) ---
try {
    $diskPerf = Get-Counter '\PhysicalDisk(*)\Avg. Disk sec/Transfer' -ErrorAction SilentlyContinue
    if ($diskPerf) {
        $io = $diskPerf.CounterSamples | Where-Object { $_.CookedValue -gt 0 } | Select-Object -First 1
        if ($io) {
            $ioMs = [math]::Round($io.CookedValue * 1000, 2)
            Write-Host "  Disk Latency: $ioMs ms"
        }
    }
} catch {}

# --- Network ---
Write-Host ""
Write-Host "[NETWORK]" -ForegroundColor Yellow
$adapters = Get-NetAdapter | Where-Object { $_.Status -eq "Up" }
foreach ($a in $adapters) {
    Write-Host "  Adapter: $($a.Name) | Link: $($a.LinkSpeed)"
    $dns = Get-DnsClientServerAddress -InterfaceIndex $a.ifIndex -AddressFamily IPv4 -ErrorAction SilentlyContinue
    if ($dns) {
        Write-Host "  DNS: $($dns.ServerAddresses -join ', ')"
    }
}
$pubIP = (Invoke-WebRequest -uri "https://ifconfig.me" -UseBasicParsing -TimeoutSec 5).Content.Trim()
Write-Host "  Public IP: $pubIP"

# --- Uptime ---
Write-Host ""
Write-Host "[UPTIME]" -ForegroundColor Yellow
$lastBoot = (Get-CimInstance Win32_OperatingSystem).LastBootUpTime
$uptime = (Get-Date) - $lastBoot
Write-Host "  Last boot: $($lastBoot.ToString('yyyy-MM-dd HH:mm:ss'))"
Write-Host "  Uptime: $($uptime.Days) days, $($uptime.Hours) hours, $($uptime.Minutes) minutes"

# --- Windows Info ---
Write-Host ""
Write-Host "[WINDOWS]" -ForegroundColor Yellow
$winVer = Get-CimInstance Win32_OperatingSystem
Write-Host "  OS: $($winVer.Caption)"
Write-Host "  Build: $($winVer.BuildNumber)"
Write-Host "  Arch: $($winVer.OSArchitecture)"

# --- Services Status ---
Write-Host ""
Write-Host "[SERVICES]" -ForegroundColor Yellow
$checkServices = @(
    @{Name="sshd"; Desc="OpenSSH Server"},
    @{Name="DiagTrack"; Desc="Telemetry"},
    @{Name="dmwappushservice"; Desc="WAP Push"},
    @{Name="SysMain"; Desc="Superfetch"},
    @{Name="wuauserv"; Desc="Windows Update"}
)
foreach ($svc in $checkServices) {
    $service = Get-Service -Name $svc.Name -ErrorAction SilentlyContinue
    if ($service) {
        $status = $service.Status
        $startup = $service.StartType
        $color = if ($status -eq "Running") { "Green" } else { "DarkGray" }
        Write-Host "  $($svc.Desc): $status ($startup)" -ForegroundColor $color
    } else {
        Write-Host "  $($svc.Desc): Not installed" -ForegroundColor DarkGray
    }
}

# --- Power Plan ---
Write-Host ""
Write-Host "[POWER]" -ForegroundColor Yellow
$powerPlan = powercfg /getactivescheme 2>$null
Write-Host "  Active plan: $($powerPlan -replace 'Power Scheme GUID: [a-f0-9-]+ ','')"
$hibernation = powercfg /a 2>$null | Select-String "Hibernation"
if ($hibernation -match "disabled") {
    Write-Host "  Hibernation: Disabled" -ForegroundColor Green
} else {
    Write-Host "  Hibernation: Enabled" -ForegroundColor Yellow
}

# --- Top 5 Memory Processes ---
Write-Host ""
Write-Host "[TOP 5 MEMORY HOGS]" -ForegroundColor Yellow
$procs = Get-Process | Sort-Object WorkingSet -Descending | Select-Object -First 5
foreach ($p in $procs) {
    $memMB = [math]::Round($p.WorkingSet / 1MB, 0)
    Write-Host "  $($p.Name): $memMB MB"
}

# --- Startup Programs ---
Write-Host ""
Write-Host "[STARTUP PROGRAMS]" -ForegroundColor Yellow
$startupApps = Get-CimInstance Win32_StartupCommand | Where-Object {
    $_.Name -notmatch "OneDrive|SecurityHealth|WindowsDefender|System32|Program Files"
}
if ($startupApps) {
    foreach ($app in $startupApps) {
        Write-Host "  - $($app.Name)" -ForegroundColor White
    }
} else {
    Write-Host "  None (clean startup)" -ForegroundColor Green
}

# --- Pending Windows Updates ---
Write-Host ""
Write-Host "[WINDOWS UPDATES]" -ForegroundColor Yellow
try {
    $updateSession = New-Object -ComObject Microsoft.Update.Session
    $searcher = $updateSession.CreateUpdateSearcher()
    $updates = $searcher.Search("IsInstalled=0")
    if ($updates.Updates.Count -gt 0) {
        Write-Host "  Pending: $($updates.Updates.Count) updates" -ForegroundColor Yellow
        foreach ($u in $updates.Updates) {
            Write-Host "    - $($u.Title)" -ForegroundColor White
        }
    } else {
        Write-Host "  [OK] Windows is up to date" -ForegroundColor Green
    }
} catch {
    Write-Host "  (Could not check - may need to restart update service)" -ForegroundColor DarkGray
}

# --- Summary ---
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Status check complete" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
